In [1]:
s = "Hi there Sam!"

In [2]:
s="Hi there Sam!"
s=s.split()
print(s);

['Hi', 'there', 'Sam!']


In [3]:
planet = "Earth"
diameter = 12742

In [4]:
planet = "Earth"
diameter = 12742
print( 'The diameter of {} is {} kilometers.' .format(planet,diameter));

The diameter of Earth is 12742 kilometers.


In [5]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [6]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

hello


In [7]:
import numpy as np

In [8]:
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [10]:
arr = np.arange(0,9).reshape(3,3)

print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
import numpy as np 
a = np.array([1,2,3]) 

print 'First array:' 
print a 
print '\n'  
b = np.array([4,5,6]) 

print 'Second array:' 
print b 
print '\n'  
# both the arrays are of same dimensions 

print 'Joining the two arrays along axis 0:' 
print np.concatenate((a,b))

SyntaxError: ignored

In [16]:
import pandas as pd

In [17]:
import pandas as pd

from numpy.random import randn
 
df = pd.DataFrame(randn(2,3), columns=['column 1', 'column 2', 'column 3'], index = ['row 1', 'row 2', 'row 3'])
print(df)

ValueError: ignored

In [18]:
import datetime

def date_generator():
  from_date = datetime.datetime.today()
  while True:
    yield from_date
    from_date = from_date - datetime.timedelta(days=1)

In [19]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [20]:
import pandas as pd  
      

lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
  
 
df = pd.DataFrame(lists, columns =['Tag', 'number']) 
print(df )

ValueError: ignored